### ISSUE TITLE
Reintroduce json linting?

### ISSUE THREAD

**Issue by kitch** [AtomLinter/linter-jshint#18]
Looks like https://github.com/AtomLinter/Linter/issues/39 was caused by https://github.com/AtomLinter/Linter/issues/67 and not by using jshint to lint json with the react editor. Thoughts on bringing it back?

**Comment by abejfehr** [comment]
I think this is weird behaviour. jshint in our gulpfile lints json files, and I installed this package specifically so I could find all the problems _before_ it got that far. Why doesn't linter-jshint just do what jshint does, instead of deciding _for_ jshint what it should and shouldn't do

**Comment by Arcanemagus** [comment]
> Why doesn't linter-jshint just do what jshint does, instead of deciding for jshint what it should and shouldn't do

Because JSHint doesn't actually _say_ that it lints JSON, so this package doesn't make it do so. If you want JSON linting you should install a JSON lint provider such as [linter-jsonlint](https://atom.io/packages/linter-jsonlint). The "JSON linting" that is done by JSHint is actually just a wrapper around an old version of that anyway, and as far as I knew only happened on `package.json` files.

**Comment by abejfehr** [comment]
It's true that it's not advertised as a feature for jshint, but I found it jarring that their behaviours are different. I've installed linter-jsonlint now, but my opinion is still that this package should match jshint.

The file that was lined by jshint for me was a not a `package.json` file, so it seems like they lint more than just those.

**Comment by Arcanemagus** [comment]
As JSHint doesn't advertize support for that I'm not enabling it. JSHint is buggy enough linting just JS code I don't really want to deal with issues from it linting JSON when they don't even officially support it.
