### ISSUE TITLE
Underline marker off when using tabs.

### ISSUE THREAD

**Issue by AlexanderOMara** [AtomLinter/linter-jshint#190]
In short, the underline marker location is off when using tabs. It appears it does not take the width of a tab into account.

![jshint-tab-vs-space](https://cloud.githubusercontent.com/assets/1740229/12213316/fc82f8ec-b643-11e5-862f-ed013abe3200.png)

Code I used for the test:

**`.jshintrc`**
```json
{
	"undef": true
}
```

**`test.js`**
```js
(function() {
	'use strict';

    undefinedFunction(); // spaces

	undefinedFunction(); // tabs
})();
```

On a side note, it also does not take the width of the symbol into account, it's always just 1 wide.

**Comment by AlexanderOMara** [comment]
For reference, [here's what the jscs plugin uses](https://github.com/AtomLinter/linter-jscs/blob/06c48403db076e842d25602c9c312b2997f8de9c/index.js#L126-L129)

```js
          const indentLevel = editor.indentationForBufferRow(line - 1);
          const startCol = editor.getTabLength() * indentLevel;
          const endCol = editor.getBuffer().lineLengthForRow(line - 1);
          const range = [[line - 1, startCol], [line - 1, endCol]];
```

**Comment by Arcanemagus** [comment]
We're simply using what `jshint` gives back to us [here](https://github.com/AtomLinter/linter-jshint/blob/v1.2.2/lib/main.coffee#L64-L65), looks like an issue needs to be filed over on the [jshint repo](https://github.com/jshint/jshint/issues).

Please link back here so anyone finding this in the future can see the resolution :wink:.

Marking as closed since this isn't an issue with the linter-jshint package.

**Comment by AlexanderOMara** [comment]
Wait, are you saying the problem is jshint does not take into account the width of the tab? Can you explain why it is the jscs plugin is using `editor.getTabLength()` to set the correct width, but this plugin does not?

**Comment by Arcanemagus** [comment]
`linter-jscs` is apparently ignoring the column reported by `jscs` and instead using the whole line, and in fact is doing it incorrectly as it would run into a related issue on the example you give above since `editor.getTabLength()` is set for the first indentation in the buffer (tabs) so it would set the error character _way_ off on the _spaces_ line. `helpers.rangeFromLineNumber()` simply calculates the length of the whitespace as a character count using regex and uses that as the start to work around this issue.

This package (linter-jshint) attempts to use the column reported by `jshint`, and simply creates a range of one character starting at that column. `rangeFromLineNumber()` could be used to start at that column and fill to the end of the line for more visibility, but would still suffer from the same issue you have reported here since it looks like `jshint` is replacing tabs with 4 spaces in its column count, leading to the start being wrong no matter what.

If you want to verify this yourself set a breakpoint [here](https://github.com/AtomLinter/linter-jshint/blob/v1.2.2/lib/main.coffee#L64) and check the value of error.character for the line where it marks the wrong character.

**Comment by Arcanemagus** [comment]
Also if you run `jshint` from a terminal it should report the same (incorrect) column.

**Comment by AlexanderOMara** [comment]
Oh look at that, jscs is off too...

Yeah I just checked jshint's terminal output, it assumes a tab is 4 characters, and incorrectly sets the column based on that.

Looks like there's been a couple of issues opened on jshint over this. I'll have to sift through them.
