### ISSUE TITLE
Can't configure to use .jshintignore file

### ISSUE THREAD

**Issue by bjornhanson** [AtomLinter/linter-jshint#302]
In our development, in addition to using a .jshintrc file, we also use a .jshintignore file. Right now this plugin isn't utilizing that, so errors are popping up where they shouldn't in Atom.

**Comment by Arcanemagus** [comment]
If you want to put together a PR implementing this, I'd be happy to review/merge it.

**Comment by alfonsomga** [comment]
We need this.

**Comment by Arcanemagus** [comment]
Okay, looked into this and apparently this is yet another bug in JSHint 😞.

When you run JSHint on a file, everything works properly and it auto-configures itself. The problem is that although we are telling JSHint what the file is that we are sending it the contents of, it ignores this and completely fails to configure itself when you feed in the contents via `stdin`.

You can replicate this with `jshint` alone:
![image](https://cloud.githubusercontent.com/assets/427137/25724238/1aff42f0-30d0-11e7-8c6c-54047b5e5769.png)

The first example is how this package sends in the content, while the second is running on the contents of the file on disk. This can't even be fixed using the `--exclude-path` argument, since it seems the issue is that the `--filename` argument is being ignored entirely for configuration purposes and is only used in the report.

**Comment by bjornhanson** [comment]
That's a bummer.

**Comment by Arcanemagus** [comment]
I'm looking into re-implementing this functionality in the linter since for some bizarre reason there are a _lot_ of people still using JSHint.
