### ISSUE TITLE
Stopped working with language-babel

### ISSUE THREAD

**Issue by haveanicedavid** [AtomLinter/linter-jshint#348]
Upon updating to the most recent version of language-babel, JSHint linting stopped working.

'Lint JSX' is currently enabled, and i'm not sure how to troubleshoot. Another JSHint plugin seems to be working, and switching the language to vanilla JS instead of Language-babel also seems to work.

Is there something else I can do to troubleshoot?

**Comment by Arcanemagus** [comment]
v3 removed the support of linting JSX code. I could find no mention on the JSHint site stating that it actually supports this, and we kept getting errors related to running on that code. I would recommend you check out other linters that _are_ meant to support that setup, such as ESLint with the proper plugins.

**Comment by Arcanemagus** [comment]
Filed an issue on `language-babel`.

**Comment by Arcanemagus** [comment]
It sounds like JSX people are terrible, and just use `.js` for JSX files, it _could_ be "fixed" so that it only marks files as `source.js.jsx` when in a JSX block, but that could lead to issues of running `source.js` linters on a file that is partially JSX.

I would recommend disabling `language-babel` if you are not using the JSX features, or just remembering to change the file language to JS on regular JS files.

**Comment by AnnanFay** [comment]
> It sounds like JSX people are terrible, and just use .js for JSX files

I realise this issue is a bit old but I am just coming across this.

@Arcanemagus The [official recommendation](https://github.com/facebook/create-react-app/issues/87) appears to be to use `.js` for JSX files.
